jfcbackend/jfcbackend/urls.py
from django.contrib import admin
from django.urls import path, include
# include here helps to go into api folder and into urls file
# to match all the urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('', include("pricePrediction.urls")),
]

jfcbackend/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('get_csrf_token/', views.get_csrf_token, name='get_csrf_token'),  

    path('login/', views.login_view, name='login'),   
    path('logout/', views.logoutUser, name='logout'),

    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    # path('profile/<username>/', views.profile, name='profile'),
    path('edit-profile/<username>/', views.edit_profile, name='edit_profile'),
    path('password_change/', views.password_change, name='password_change'),

    path('password_reset/', views.forgot_password_email, name='password_reset'),
    path('reset/<uidb64>/<token>/', views.passwordResetConfirm, name='password_reset_confirm'), 

    path('fav/<int:id>/', views.favourite_add, name="favourite_add"),
    path('profile/<username>/favourites/', views.favourites_list, name="favourites_list"),
    path('', views.home, name='home'),

    path('get_username/', views.get_username, name='get_username'),
]

jfcbackend/templates/activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

jfcbackend/templates/all_house_price.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <title>All Post</title>
</head>
<body>
    <div class="container my-4 post-wrapper">
        <!-- Search Start -->
        <div class="jumbotron border shadow">
            <div class="row">
                <div class="col-md-8 offset-2">
                    <form>
                        <div class="input-group">
                            <input name="q" type="text" placeholder="Search" class="form-control form-control-lg" />
                            <div class="input-group-append">
                            <input name="ft" type="text" placeholder="Search" class="form-control form-control-lg" />
                            <div class="input-group-append">
                            <input name="fm" type="text" placeholder="Search" class="form-control form-control-lg" />
                            <div class="input-group-append">
                                <button class="btn btn-dark btn-lg">Search</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- End Search -->
        <h3>All Posts</h3>
        <p>
            <a class="btn btn-success" href="/add">Add Data</a>
        </p>
        {% block content %}
            {% if graph %}
                <img src = "data:image/png;base64, {{graph|safe}}">
            {% endif %}
        {% endblock content %}
    </br>
        {% for house in page.object_list %}
        <strong> {{ house }} </strong>
        {% if request.user.is_authenticated %}
        <!-- {% if fav %}
        <div>
            <a href="{% url 'users:favourites_list' house.id %}">Remove Favourites</a>
        </div>
        {% else %} -->
        <div>
            <a href="{% url 'users:favourite_add' house.id %}">Add to Favourites</a> 
        </div>
        <!-- {% endif %} -->
        
        {% else %}
        <div>
            <a href="{% url 'users:register' %}">Add to Favourites (Register first)</a> 
        </div>
        {% endif %}
        <u1>
        <li>{{ house.town }}</li>
        <li>{{ house.flat_type }}</li>
        <li>{{ house.block }}</li>
        <li>{{ house.street_name }}</li>
        <li>{{ house.floor_area_sqm }}</li>
        <li>{{ house.flat_model }}</li>
        <li>{{ house.remaining_lease }}</li>
        <li>{{ house.resale_price }}</li>
        </u1>
        </br>
        {% endfor %}

	<div class= "page-links">
            {% if page.has_previous %}
                <a href="?page={{ page.previous_page_number }}">Previous Page</a>
            {% endif %}

            {% for i in page.paginator.page_range %}
                {% if page.number == i %}
                    <span class="current">{{ i }}</span>
                {% else %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            {% endfor %}
            
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}">Next Page</a>
            {% endif %}
            </div>
        </div>
</script>   
</body>
</html>

jfcbackend/templates/favourites.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div>
    <section>
        <div>
            <h1>User favourited Houses</h1>
            <p>Here you can remove or view the favourites posts you have added</p>
        </div>
    </section>
    <div>
        <div>
            {% for house in new %}
            <div>
                <h2>{{house.id}}</h2>
                <h2>{{house.block}} {{house.street_name}}</h2>
            </div>
            <div>
                <h2>{{house.flat_type}}</h2>
            </div>
            <div>
                <a href="{% url 'users:favourite_add' house.id %}">Remove</a>
            </div>
            {% endfor %}
          </div>
    </div>
</div>

{% endblock content %}

jfcbackend/templates/home.html
{% extends 'main.html' %}

{% block content %}
<h1>Home Template</h1>

{% if request.user.is_authenticated %}
<p>Hello {{request.user}}</p>
<a href="{% url 'users:logout' %}">Logout</a>
{% else %}
<a href="{% url 'users:login' %}" >Login</a>
{% endif %}

{% endblock content %}

jfcbackend/templates/login_register.html
<style>
    body {
      background-image: url('/jfcbackend/static/images/1.jpg');
      background-size: cover;
      background-position: center;
      background-repeat: no-repeat;
      background-color: #f8f8f8;
      font-family: Arial, sans-serif;
    }
    form {
      background-color: #fff;
      padding: 30px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
      width: 400px;
      margin: 50px auto;
    }
    h1 {
      text-align: center;
      font-size: 28px;
      margin-bottom: 30px;
      color: #555;
    }
    label {
      display: block;
      font-size: 18px;
      margin-bottom: 10px;
      color: #777;
    }
    /*input[type="text"],
    input[type="password"] {
      width: 100%;
      padding: 10px;
      margin-bottom: 20px;
      border-radius: 3px;
      border: none;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
      font-size: 16px;
    }*/
    input[type="submit"] {
      background-color: #ff5a5e;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 3px;
      font-size: 18px;
      cursor: pointer;
      margin-top: 20px;
      transition: background-color 0.3s ease;
    }
    input[type="submit"]:hover {
      background-color: #ff5a5e;
    }
    .forgot-password {
      display: block;
      text-align: right;
      font-size: 16px;
      margin-top: 10px;
      color: #555;
    }
    .forgot-password a {
      color: #ff5a5e;
      text-decoration: none;
      transition: color 0.3s ease;
    }
    .forgot-password a:hover {
      color: #ff5a5e;
    }
    .register {
      display: block;
      text-align: center;
      font-size: 16px;
      margin-top: 30px;
      color: #555;
    }
    .register a {
      color: #ff5a5e;
      text-decoration: none;
      transition: color 0.3s ease;
    }
    .register a:hover {
      color: #ff5a5e;
    }
    .home-button {
      display: block;
      text-align: center;
      font-size: 18px;
      margin-top: 30px;
      color: #555;
    }
    .home-button a {
      display: inline-block;
      background-color: #ff5a5e;
      color: #fff;
      padding: 10px 20px;
      border-radius: 3px;
      font-size: 18px;
      text-decoration: none;
      transition: background-color 0.3s ease, color 0.3s ease;
    }
    .home-button a:hover {
      background-color: #ff5a5e;
      color: #fff;
    }
    input[type="text"],
    input[type="password"],
    input[type="email"],
    select {
      width: 100%;
      padding: 10px;
      margin-bottom: 20px;
      border-radius: 3px;
      border: none;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
      font-size: 16px;
    }
    
  </style>

{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<style>
  body {
    background-image: url('{% static "images/1.jpg" %}');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-color: #f8f8f8;
    font-family: Arial, sans-serif;
  }
</style>
{% if page == 'login' %}
<form method="POST" action=''>
  {% csrf_token %}
  <h1>JFC Property Login</h1>
  <label for="username">Email:</label>
  <input type="text" id="username" name="username" required>
  <label for="password">Password:</label>
  <input type="password" id="password" name="password" required>
  <input type="submit" value="Login">
  <span class="forgot-password">
    <a href="{% url 'users:password_reset' %}">Forgot password?</a>
  </span>
  <span class="register">
    Don't have an account? <a href="{% url 'users:register' %}">Register now</a>
  </span>
</form>

<span class="home-button">
  <a href="http://127.0.0.1:3000/">Return to Home Page</a>
</span>
{% else %}
<div>
  <form method="POST" action=''>
    {% csrf_token %}
    <h1>Register An Account</h1>
    {{ form|crispy }}
    <input type="submit" value="Register" />
  </form>
  <span class="home-button">
    <a href="{% url 'users:login' %}">Back to Log in</a>
  </span>
</div>
{% endif %}


{% endblock content %}

jfcbackend/templates/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>JFC Website</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{message}}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block content %}

    {% endblock %}
    
</body>
</html>

jfcbackend/templates/password_reset.html
<style>
  body {
    background-image: url('/jfcbackend/static/images/1.jpg');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-color: #f8f8f8;
    font-family: Arial, sans-serif;
  }
  .content-section {
    background-color: #fff;
    padding: 30px;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    width: 400px;
    margin: 50px auto;
  }
  h2 {
    text-align: center;
    font-size: 28px;
    margin-bottom: 30px;
    color: #555;
  }
  label {
    display: block;
    font-size: 18px;
    margin-bottom: 10px;
    color: #777;
  }
  input[type="text"],
  input[type="password"] {
    width: 100%;
    padding: 10px;
    margin-bottom: 20px;
    border-radius: 3px;
    border: none;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
    font-size: 16px;
  }
  button[type="submit"] {
    background-color: #ff5a5e;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 3px;
    font-size: 18px;
    cursor: pointer;
    margin-top: 20px;
    transition: background-color 0.3s ease;
  }
  button[type="submit"]:hover {
    background-color: #ff5a5e;
  }
  p {
    font-size: 16px;
    color: #555;
  }
  a {
    color: #ff5a5e;
    text-decoration: none;
    transition: color 0.3s ease;
  }
  a:hover {
    color: #ff5a5e;
  }
  hr {
    border-top: 1px solid #ddd;
    margin-bottom: 30px;
  }
  .back-to-login {
    background-color: #ff5a5e;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 3px;
    font-size: 18px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  /* Add this new CSS rule for the "Back to Login" button hover effect */
  .back-to-login:hover {
    background-color: #ff5a5e;
    opacity: 0.9;
  }
</style>


{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<style>
  body {
    background-image: url('{% static "images/1.jpg" %}');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-color: #f8f8f8;
    font-family: Arial, sans-serif;
  }
</style>
<div class="content-section">
  <h2>Reset Password</h2>
  <hr>
  <p>Forgotten your password? Enter your email address below, and we will email instructions for setting a new one.</p>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-outline-info" type="submit">Send email</button>
  </form>
  <div class="mt-3 text-center">
    <a class="back-to-login" href="{% url 'users:login' %}">Back to Login</a>
  </div>
</div>
{% endblock %}

jfcbackend/templates/password_reset_confirm.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <h2> Password Reset Confirmation</h2>
    <p>Please enter your new password.</p>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-outline-info" type="submit">Reset password</button>
    </form>
</div> 
{% endblock %}

jfcbackend/templates/profile.html
<style>
    body {
      background-color: #f8f8f8;
      font-family: Arial, sans-serif;
    }
    form {
      background-color: #fff;
      padding: 30px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
      width: 400px;
      margin: 50px auto;
    }
    h1 {
      text-align: center;
      font-size: 28px;
      margin-bottom: 30px;
      color: #555;
    }
    label {
      display: block;
      font-size: 18px;
      margin-bottom: 10px;
      color: #777;
    }
    input[type="text"],
    input[type="password"] {
      width: 100%;
      padding: 10px;
      margin-bottom: 20px;
      border-radius: 3px;
      border: none;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
      font-size: 16px;
    }
    .update {
      background-color: #ff5a5e;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 3px;
      font-size: 18px;
      cursor: pointer;
      margin-top: 20px;
      transition: background-color 0.3s ease;
    }
    input[type="submit"]:hover {
      background-color: #ff5a5e;
    }
    .change-password {
      display: block;
      text-align: right;
      font-size: 16px;
      margin-top: 10px;
      color: #555;
    }
    .change-password a {
      color: #ff5a5e;
      text-decoration: none;
      transition: color 0.3s ease;
    }
    .change-password a:hover {
      color: #ff5a5e;
    }
    .register {
      display: block;
      text-align: center;
      font-size: 16px;
      margin-top: 30px;
      color: #555;
    }
    .register a {
      color: #ff5a5e;
      text-decoration: none;
      transition: color 0.3s ease;
    }
    .register a:hover {
      color: #ff5a5e;
    }
  </style>

{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div className="col-lg-12 mb10">
    <div className="breadcrumb_content style2">
      <h2 className="breadcrumb_title">My Profile</h2>
      <p>We are glad to see you again!</p>
    </div>
</div>

<div>
    <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}

        <div className="col-lg-12 mb10">
            <div className="breadcrumb_content style2">
              <h2 className="breadcrumb_title">Profile Information</h2>
            </div>
        </div>

        <div class="media">
            <div class="media-body">
                <h4 class="account-heading">
                    Username: 
                    {{form.instance.username}}
                </h4>
                <h4 class="account-heading">
                    Email: {{form.instance.email}}
                </h4>
            </div>
        </div>

        {% if user.username == form.instance.username %}
            <fieldset class="form-group">
                <legend class="border-bottom-mb-4">
                    Edit Profile Information
                </legend>
                <div class="form-group col-md-6 mb-0">
                    {{ form.username|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.email|as_crispy_field }}
                </div>
                <a class='change-password' href="{% url 'users:password_change' %}">Change Password?</a>
            </fieldset>
            <div class="form-group">
                <button class="update" type="submit">Update</button>
            </div>
            {% endif %}
    </form>
</div>

{% endblock content %}

jfcbackend/templates/template_reset_password.html
{% autoescape off %}
Hello {{ user.username }},

We received a request to reset the password for your account for this email address. To initiate the password reset process for you account, click the link below:

http://127.0.0.1:3000/confirm-reset-password/{{uid}}/{{token}}

This link can only be used once. If you need to reset your password again, please visit http://127.0.0.1:3000 and request another password reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
JFC Housing

{% endautoescape %}